// gq new and gq sync on the files a site shares with the blueprint, driven
// through run(): the generated sections of AGENTS.md and .gitignore, the
// managed keys of package.json, and the create-once glossary and README.
// What the site owns in each (content outside the markers, every other
// package key, a create-once file once written) is never touched.
import assert from "node:assert/strict";
import { appendFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";

import { createFixtureSite } from "./support/fixture-site.mjs";
import { hash, newSite, readSite, snapshot } from "./support/new-site.mjs";

const IGNORE_BEGIN =
  "# BEGIN gq: generated by @getquick/site; gq sync rewrites this section. Add site rules outside it.";
const IGNORE_SECTION = [
  IGNORE_BEGIN,
  ".DS_Store",
  "*.log",
  "node_modules/",
  ".pnpm-store/",
  ".env",
  ".env.local",
  ".env.*.local",
  ".dev.vars",
  ".dev.vars.*",
  ".env.keys",
  ".env.*.keys",
  ".vscode/settings.json",
  "",
  "# Local reports and generated output",
  "dist/",
  "playwright-report/",
  "test-results/",
  "coverage/",
  "",
  "# DDEV / local tooling state",
  ".ddev/.global/",
  ".ddev/.data/",
  "",
  "# vite-plus generated git-hook shims (regenerated by `pnpm install`'s prepare script)",
  ".vite-hooks/_/",
  "",
  "# Alchemy local logs/cache (state lives in the Cloudflare state store)",
  ".alchemy/",
  "",
  "# Wrangler build output and local state",
  ".wrangler/",
  "# END gq",
  "",
].join("\n");
const AGENTS_BEGIN =
  "<!-- BEGIN gq: generated by @getquick/site; gq sync rewrites this section. Add site guidance outside it. -->";
const AGENTS_END = "<!-- END gq -->";

// The site's lock, parsed.
async function readLock(root) {
  return JSON.parse(await readSite(root, "gq.lock.json"));
}

async function writeLock(root, lock) {
  await writeFile(join(root, "gq.lock.json"), `${JSON.stringify(lock, null, 2)}\n`);
}

test("gq new writes AGENTS.md and .gitignore as their generated sections, hashed in the lock", async () => {
  const site = await newSite();

  assert.equal(await readSite(site.root, ".gitignore"), IGNORE_SECTION);
  const agents = await readSite(site.root, "AGENTS.md");
  assert.ok(agents.startsWith(`${AGENTS_BEGIN}\n`), agents);
  assert.ok(agents.endsWith(`\n${AGENTS_END}\n`), agents);
  assert.match(agents, /^## Managed files$/mu);
  assert.match(agents, /^### Issue tracker$/mu);

  const lock = await readLock(site.root);
  assert.deepEqual(lock.sections, {
    ".gitignore": hash(IGNORE_SECTION),
    "AGENTS.md": hash(agents),
  });
});

test("an edit inside a generated section stops gq sync with a diff, and nothing is written", async () => {
  const site = await newSite();
  const ignore = IGNORE_SECTION.replace("coverage/\n", "coverage/\n.cache/\n");
  await writeFile(join(site.root, ".gitignore"), `/vendor\n\n${ignore}`);
  const before = await snapshot(site.root);
  const diff = [
    ".gitignore (generated section): edited since gq last wrote it (gq.lock.json); gq sync would write:",
    "--- .gitignore",
    "+++ .gitignore (gq sync)",
    "@@ -19,7 +19,6 @@",
    " playwright-report/",
    " test-results/",
    " coverage/",
    "-.cache/",
    " ",
    " # DDEV / local tooling state",
    " .ddev/.global/",
    "",
  ].join("\n");

  for (const argv of [["sync"], ["sync", "--check"]]) {
    const result = await site.run(argv);
    assert.equal(result.code, 1);
    assert.equal(result.stdout, `gq.ops.json: up to date (schema v1).\n${diff}`);
    assert.equal(
      result.stderr,
      "gq: Local edits to managed files: .gitignore. gq sync writes nothing until each is " +
        "reverted, or deleted to be regenerated.\n",
    );
    assert.deepEqual(await snapshot(site.root), before);
  }
});

// A site an older gq generated, whose AGENTS.md section the installed
// blueprint has since changed: the lock records the section gq wrote then.
async function siteWithOldAgentsSection() {
  const site = await newSite();
  const section = await readSite(site.root, "AGENTS.md");
  const old = section.replace("## Safety\n", "## Safety rules\n");
  await writeFile(join(site.root, "AGENTS.md"), old);
  const lock = await readLock(site.root);
  lock.gq = "0.11.0";
  lock.sections["AGENTS.md"] = hash(old);
  await writeLock(site.root, lock);
  return { ...site, section, old };
}

test("a template change to an unedited section is applied, keeping the site's content around it", async () => {
  const site = await siteWithOldAgentsSection();
  const above = "# Acme workspace guidance\n\nAcme is a content site.\n\n";
  const below = "\n## Acme plugins\n\n- `acme-blocks` owns the blocks.\n";
  await writeFile(join(site.root, "AGENTS.md"), `${above}${site.old}${below}`);
  const ignoreBelow = "\n# Acme\n/apps/cms/web/app/uploads/\n";
  await appendFile(join(site.root, ".gitignore"), ignoreBelow);
  const before = await snapshot(site.root);

  const check = await site.run(["sync", "--check"]);
  assert.equal(check.code, 1);
  assert.equal(
    check.stdout,
    [
      "gq.ops.json: up to date (schema v1).",
      "AGENTS.md: pending, gq sync would update its generated section.",
      "gq.lock.json: pending, gq sync would update it.",
      "",
    ].join("\n"),
  );
  assert.deepEqual(await snapshot(site.root), before);

  const sync = await site.run(["sync"]);
  assert.equal(sync.code, 0, sync.stderr);
  assert.equal(
    sync.stdout,
    [
      "gq.ops.json: up to date (schema v1).",
      "AGENTS.md: updated (generated section).",
      "gq.lock.json: updated.",
      "",
    ].join("\n"),
  );
  assert.equal(await readSite(site.root, "AGENTS.md"), `${above}${site.section}${below}`);
  assert.equal(await readSite(site.root, ".gitignore"), `${IGNORE_SECTION}${ignoreBelow}`);
  assert.equal((await readLock(site.root)).sections["AGENTS.md"], hash(site.section));

  const again = await site.run(["sync", "--check"]);
  assert.equal(again.code, 0, again.stdout);
  for (const { fetch, exec } of [check, sync]) {
    assert.deepEqual(fetch.requests, []);
    assert.deepEqual(exec.calls, []);
  }
});

test("gq sync appends a generated section to a file that has none, keeping the file's content", async () => {
  const site = await createFixtureSite({
    ops: { schemaVersion: 1, project: "acme", variant: "content" },
    files: { ".gitignore": "/vendor\n.cache/" },
  });

  const result = await site.run(["sync"]);

  assert.equal(result.code, 0, result.stderr);
  assert.match(result.stdout, /^\.gitignore: updated \(generated section\)\.$/mu);
  assert.equal(await readSite(site.root, ".gitignore"), `/vendor\n.cache/\n\n${IGNORE_SECTION}`);
  assert.equal((await site.run(["sync", "--check"])).code, 0);
});

test("gq sync refuses a generated section whose markers it can't pair", async () => {
  const site = await newSite();
  const ignore = await readSite(site.root, ".gitignore");
  await writeFile(join(site.root, ".gitignore"), ignore.replace("# END gq\n", ""));
  const before = await snapshot(site.root);

  const result = await site.run(["sync", "--check"]);

  assert.equal(result.code, 1);
  assert.equal(
    result.stderr,
    `gq: .gitignore must hold gq's generated section once, from a "# BEGIN gq…" line to a ` +
      '"# END gq" line. Restore the markers, or remove both and gq sync appends the section.\n',
  );
  assert.deepEqual(await snapshot(site.root), before);
});

// The root scripts that wrap gq or run the generated deploy files (the
// release step and the checks gq verify runs), as Lombardi has them.
const GQ_SCRIPTS = {
  setup: "gq setup",
  doctor: "gq doctor",
  verify: "gq verify",
  "test:scripts": "node --test scripts/*.test.mjs",
  "cms:dev": "gq sigillo run local -- gq cms start",
  "cms:dev:raw": "gq cms start",
  "cms:dev:foreground": "gq sigillo run local -- gq cms start --foreground",
  "cms:dev:status": "gq cms status",
  "cms:stop": "gq cms stop",
  "cms:describe": "gq cms describe",
  "cms:composer": "gq sigillo run local -- gq cms composer install",
  "cms:composer:update": "gq sigillo run local -- gq cms composer update",
  "cms:composer:reinstall": "gq sigillo run local -- gq cms composer reinstall",
  "cms:test": "gq cms composer test",
  "cms:lint": "gq cms composer lint",
  "db:sync": "gq sigillo run staging -- gq db sync",
  "db:backup": "gq sigillo run staging -- gq db backup",
  "deploy:frontend": "gq sigillo run staging -- pnpm --dir infra run deploy:frontend",
  "deploy:frontend:raw": "pnpm --dir infra run deploy:frontend",
  "plan:frontend": "pnpm --dir infra run plan:frontend",
  "infra:check": "pnpm --dir infra run check",
  push: "gq release push",
  release: "gq release prepare",
  "release:prepare": "gq release prepare",
  "release:tag": "gq release tag",
  "version:check": "gq version check",
  "version:sync": "gq version sync",
  prepare: "vp config --no-agent --hooks-dir .vite-hooks",
  ops: "gq sigillo run staging -- gq",
  "ploi:status": "gq sigillo run staging -- gq ploi provision --dry-run",
  "ploi:provision": "gq sigillo run staging -- gq ploi provision",
  "ploi:release": "gq sigillo run staging -- gq ploi release",
  "cf:releases": "gq sigillo run operations -- gq cloudflare releases",
  "cf:media": "gq sigillo run operations -- gq cloudflare media",
  "ploi:media": "gq sigillo run staging -- gq ploi media",
  "git:artifacts": "gq git artifacts",
  "ci:deploy": "gq sigillo run staging -- gq ci deploy",
  "ci:runs": "gq sigillo run staging -- gq ci runs",
  "ci:check": "pnpm --dir infra/ci run check",
  "cf:ci": "gq sigillo run operations -- gq cloudflare ci",
  "cf:deploy-token": "gq sigillo run operations -- gq cloudflare deploy-token",
  "github:setup": "gq sigillo run staging -- gq github setup",
  "ploi:log": "gq sigillo run staging -- gq ploi api sites.log-site --per-page 5",
  "sigillo:login": "gq sigillo login",
  "sigillo:setup": "gq sigillo setup local",
  "sigillo:list:local": "gq sigillo secrets local",
  "sigillo:list:ops": "gq sigillo secrets operations",
  "sigillo:list:staging": "gq sigillo secrets staging",
};
const MANAGED_KEYS = [
  ...Object.keys(GQ_SCRIPTS).map((name) => `scripts.${name}`),
  "engines.node",
  "packageManager",
];

async function readPackage(root) {
  return JSON.parse(await readSite(root, "package.json"));
}

test("gq new writes package.json with the managed keys, each hashed in the lock", async () => {
  const site = await newSite();

  const pkg = await readPackage(site.root);
  assert.deepEqual(pkg, {
    name: "acme",
    version: "0.0.0",
    private: true,
    type: "module",
    scripts: GQ_SCRIPTS,
    engines: { node: ">=22.12.0" },
    packageManager: "pnpm@12.6.0",
  });
  assert.equal(await readSite(site.root, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`);
  const lock = await readLock(site.root);
  assert.deepEqual(Object.keys(lock.keys), ["package.json"]);
  assert.deepEqual(Object.keys(lock.keys["package.json"]), MANAGED_KEYS);
  assert.equal(lock.keys["package.json"]["scripts.verify"], hash('"gq verify"'));
  assert.equal(lock.keys["package.json"].packageManager, hash('"pnpm@12.6.0"'));
});

test("an edit to a managed package key stops gq sync with a diff, and nothing is written", async () => {
  const site = await newSite();
  const pkg = await readPackage(site.root);
  pkg.scripts.verify = "gq verify --skip php";
  await writeFile(join(site.root, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`);
  const before = await snapshot(site.root);

  for (const argv of [["sync"], ["sync", "--check"]]) {
    const result = await site.run(argv);
    assert.equal(result.code, 1);
    assert.equal(
      result.stdout,
      [
        "gq.ops.json: up to date (schema v1).",
        "package.json (managed keys scripts.verify): edited since gq last wrote it (gq.lock.json); gq sync would write:",
        "--- package.json",
        "+++ package.json (gq sync)",
        "@@ -6,7 +6,7 @@",
        '   "scripts": {',
        '     "setup": "gq setup",',
        '     "doctor": "gq doctor",',
        '-    "verify": "gq verify --skip php",',
        '+    "verify": "gq verify",',
        '     "test:scripts": "node --test scripts/*.test.mjs",',
        '     "cms:dev": "gq sigillo run local -- gq cms start",',
        '     "cms:dev:raw": "gq cms start",',
        "",
      ].join("\n"),
    );
    assert.equal(
      result.stderr,
      "gq: Local edits to managed files: package.json. gq sync writes nothing until each is " +
        "reverted, or deleted to be regenerated.\n",
    );
    assert.deepEqual(await snapshot(site.root), before);
  }
});

test("a template change to an unedited package key is applied, leaving every other key as it was", async () => {
  const site = await newSite();
  // As an older gq wrote it: an older pnpm pin, no ploi:log script yet, and
  // two scripts the blueprint has since retired, one the site has edited.
  const pkg = await readPackage(site.root);
  delete pkg.scripts["ploi:log"];
  pkg.scripts = {
    dev: "pnpm --filter @acme/frontend dev",
    "ploi:legacy": "gq ploi legacy",
    ...pkg.scripts,
    "cf:old": "gq cloudflare old --mine",
    lint: "vp lint",
  };
  pkg.engines = { pnpm: ">=12", ...pkg.engines };
  // The site's own keys, formatted its own way.
  const old = `${JSON.stringify(pkg, null, 2)}\n`
    .replace('"pnpm@12.6.0"', '"pnpm@12.5.0"')
    .replace(
      '  "type": "module",\n',
      '  "type": "module",\n  "description": "Acme\\u2019s site",\n  "files": ["dist", "src"],\n',
    )
    .replace(
      /\n\}\n$/u,
      ',\n  "devDependencies": { "@getquick/site": "0.11.0", "vite-plus": "catalog:" }\n}\n',
    );
  await writeFile(join(site.root, "package.json"), old);
  const lock = await readLock(site.root);
  lock.gq = "0.11.0";
  lock.keys["package.json"].packageManager = hash('"pnpm@12.5.0"');
  delete lock.keys["package.json"]["scripts.ploi:log"];
  lock.keys["package.json"]["scripts.ploi:legacy"] = hash('"gq ploi legacy"');
  lock.keys["package.json"]["scripts.cf:old"] = hash('"gq cloudflare old"');
  await writeLock(site.root, lock);
  const before = await snapshot(site.root);

  const check = await site.run(["sync", "--check"]);
  assert.equal(check.code, 1);
  assert.equal(
    check.stdout,
    [
      "gq.ops.json: up to date (schema v1).",
      "package.json: pending, gq sync would update its managed keys scripts.ploi:log, " +
        "packageManager, scripts.ploi:legacy.",
      "gq.lock.json: pending, gq sync would update it.",
      "",
    ].join("\n"),
  );
  assert.deepEqual(await snapshot(site.root), before);

  const sync = await site.run(["sync"]);
  assert.equal(sync.code, 0, sync.stderr);
  assert.equal(
    sync.stdout,
    [
      "gq.ops.json: up to date (schema v1).",
      "package.json: updated (managed keys scripts.ploi:log, packageManager, scripts.ploi:legacy).",
      "gq.lock.json: updated.",
      "",
    ].join("\n"),
  );
  const expected = old
    .replace('"pnpm@12.5.0"', '"pnpm@12.6.0"')
    .replace('\n    "ploi:legacy": "gq ploi legacy",', "")
    .replace(
      '    "lint": "vp lint"\n',
      '    "lint": "vp lint",\n    "ploi:log": "gq sigillo run staging -- gq ploi api sites.log-site --per-page 5"\n',
    );
  assert.equal(await readSite(site.root, "package.json"), expected);
  assert.deepEqual(Object.keys((await readLock(site.root)).keys["package.json"]), MANAGED_KEYS);
  assert.equal((await site.run(["sync", "--check"])).code, 0);
  for (const { fetch, exec } of [check, sync]) {
    assert.deepEqual(fetch.requests, []);
    assert.deepEqual(exec.calls, []);
  }
});

test("gq sync adds the managed keys to a package.json without them, keeping its indentation", async () => {
  const own = { name: "acme", version: "1.2.3", dependencies: { astro: "^5.0.0" } };
  const site = await createFixtureSite({
    ops: { schemaVersion: 1, project: "acme", variant: "content" },
    files: { "package.json": `${JSON.stringify(own, null, "\t")}\n` },
  });

  const result = await site.run(["sync"]);

  assert.equal(result.code, 0, result.stderr);
  assert.match(result.stdout, /^package\.json: updated \(managed keys scripts\.setup, /mu);
  const written = await readSite(site.root, "package.json");
  const expected = {
    ...own,
    scripts: GQ_SCRIPTS,
    engines: { node: ">=22.12.0" },
    packageManager: "pnpm@12.6.0",
  };
  assert.equal(written, `${JSON.stringify(expected, null, "\t")}\n`);
  assert.equal((await site.run(["sync", "--check"])).code, 0);
});

test("gq sync refuses a package.json that isn't a JSON object", async () => {
  const site = await newSite();
  await writeFile(join(site.root, "package.json"), '{ "name": "acme", }\n');
  const before = await snapshot(site.root);

  const result = await site.run(["sync"]);

  assert.equal(result.code, 1);
  assert.match(result.stderr, /^gq: package\.json is not a valid JSON object: /u);
  assert.deepEqual(await snapshot(site.root), before);
});

test("gq new writes the create-once glossary and README, recorded in the lock as created", async () => {
  const site = await newSite();

  const context = await readSite(site.root, "CONTEXT.md");
  assert.match(context, /^# acme$/mu);
  assert.match(context, /^## Language$/mu);
  assert.doesNotMatch(context, /\{\{/u);
  const readme = await readSite(site.root, "README.md");
  assert.match(readme, /^# acme$/mu);
  assert.doesNotMatch(readme, /\{\{/u);
  assert.deepEqual((await readLock(site.root)).created, [
    "CONTEXT.md",
    "README.md",
    "deploy/ploi/admin.d/README.md",
    "gq.ops.json",
  ]);
});

test("gq sync leaves an edited or deleted create-once file alone", async () => {
  const site = await newSite();
  await writeFile(join(site.root, "README.md"), "# Acme\n\nOur site.\n");
  await rm(join(site.root, "CONTEXT.md"));
  const before = await snapshot(site.root);

  for (const argv of [["sync", "--check"], ["sync"]]) {
    const result = await site.run(argv);
    assert.equal(result.code, 0, result.stderr);
    assert.equal(
      result.stdout,
      "gq.ops.json: up to date (schema v1).\nManaged files: up to date.\n",
    );
    assert.deepEqual(await snapshot(site.root), before);
  }
});

test("gq sync --recreate restores an edited or deleted create-once file", async () => {
  const site = await newSite();
  const [context, readme] = await Promise.all(
    ["CONTEXT.md", "README.md"].map((path) => readSite(site.root, path)),
  );
  await writeFile(join(site.root, "README.md"), "# Acme\n\nOur site.\n");
  await rm(join(site.root, "CONTEXT.md"));
  const lock = await readSite(site.root, "gq.lock.json");
  const before = await snapshot(site.root);
  const argv = ["sync", "--recreate", "README.md", "--recreate", "CONTEXT.md"];

  const check = await site.run([...argv, "--check"]);
  assert.equal(check.code, 1);
  assert.equal(
    check.stdout,
    [
      "gq.ops.json: up to date (schema v1).",
      "CONTEXT.md: pending, gq sync would create it.",
      "README.md: pending, gq sync would update it.",
      "",
    ].join("\n"),
  );
  assert.deepEqual(await snapshot(site.root), before);

  const sync = await site.run(argv);
  assert.equal(sync.code, 0, sync.stderr);
  assert.equal(
    sync.stdout,
    "gq.ops.json: up to date (schema v1).\nCONTEXT.md: created.\nREADME.md: updated.\n",
  );
  assert.equal(await readSite(site.root, "CONTEXT.md"), context);
  assert.equal(await readSite(site.root, "README.md"), readme);
  assert.equal(await readSite(site.root, "gq.lock.json"), lock);
});

test("gq sync --recreate refuses a path the blueprint doesn't create once", async () => {
  const site = await newSite();
  const before = await snapshot(site.root);

  for (const path of [".mise.toml", "gq.ops.json", "docs/adr/0001-use-astro.md"]) {
    const result = await site.run(["sync", "--recreate", path]);
    assert.equal(result.code, 1);
    assert.equal(
      result.stderr,
      `gq: gq sync can't recreate ${path}: --recreate takes a file the blueprint creates once ` +
        "(CONTEXT.md, README.md, deploy/ploi/admin.d/README.md).\n",
    );
  }
  const manifestOnly = await site.run(["sync", "--manifest", "--recreate", "README.md"]);
  assert.equal(manifestOnly.code, 1);
  assert.equal(
    manifestOnly.stderr,
    "gq: gq sync --manifest syncs only gq.ops.json; drop --recreate or --manifest.\n",
  );
  assert.deepEqual(await snapshot(site.root), before);
});

test("gq sync creates a missing create-once file the lock doesn't record", async () => {
  const site = await createFixtureSite({
    ops: { schemaVersion: 1, project: "acme", variant: "content" },
    files: { "README.md": "# Acme\n" },
  });

  const result = await site.run(["sync"]);

  assert.equal(result.code, 0, result.stderr);
  assert.match(result.stdout, /^CONTEXT\.md: created\.$/mu);
  assert.doesNotMatch(result.stdout, /^README\.md/mu);
  assert.equal(await readSite(site.root, "README.md"), "# Acme\n");
  assert.deepEqual((await readLock(site.root)).created, [
    "CONTEXT.md",
    "README.md",
    "deploy/ploi/admin.d/README.md",
    "gq.ops.json",
  ]);
  assert.match(await readSite(site.root, "CONTEXT.md"), /^# acme$/mu);
});
