#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# gq-smoke, up: the phase 2 gate (#7). Generates the throwaway content site
# gq-smoke with the published `gq new`, verifies it, provisions it with the
# existing gq commands, and releases it from a `v*` tag through its CI Worker.
# Tear it down with scripts/smoke/gq-smoke-down.sh.
#
# Run from anywhere: scripts/smoke/gq-smoke-up.sh. Every stage is safe to
# re-run: the gq commands are idempotent and the rest checks before acting.
# Secrets only ever go to Sigillo; the state file holds public values only.

TOTAL_STAGES=16

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/gq-smoke"
mkdir -p "$STATE_DIR"
ENV_FILE="$STATE_DIR/wizard.env"

PROJECT=gq-smoke
REPOSITORY=Quick-Release/gq-smoke
SIGILLO_API=https://secrets.getquick.io
SIGILLO_ORG=01M2V5A7MYQ1C4482Z3075JZ7C          # GETQUICK
SIGILLO_PROJECT_NAME="GQ Smoke"
LOMBARDI_SIGILLO_PROJECT=01M32W12VJR8EDZKGZ4DJP5GK5
# Lombardi's Ploi server, Cloudflare account and the bnq.pt staging zone.
PLOI_SERVER_ID=102329
CF_ACCOUNT_ID=8f38791a8c37b182239af2a385ab3c31
CF_ZONE_ID=60c031fb6f81fae300c625224c39c758
CF_ZONE_NAME=bnq.pt
ADMIN_HOST=$PROJECT-cms.$CF_ZONE_NAME
FRONTEND_HOST=$PROJECT-fe.$CF_ZONE_NAME
MEDIA_HOST=$PROJECT-media.$CF_ZONE_NAME

# site CMD... runs CMD in the generated site's root.
site() { (cd "$SITE_DIR" && "$@"); }

# run CMD... runs CMD in the site root, offering a retry when it fails.
run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  until site "$@"; do
    warn "That failed."
    confirm "Retry?" || { warn "Stopped. Fix it and re-run the wizard: finished stages are skipped or idempotent."; exit 1; }
  done
}

# sig ARGS... runs the site's Sigillo CLI against GETQUICK's Sigillo.
sig() { site ./node_modules/.bin/sigillo "$@" --api-url "$SIGILLO_API"; }

# has_secret ENVIRONMENT NAME: the site's Sigillo environment (gq.ops.json
# name: local, operations or staging) has NAME. Lists names, never values.
has_secret() { site pnpm --silent exec gq sigillo secrets "$1" 2>/dev/null | grep -qw "$2"; }

# The project ID of the Sigillo project named $SIGILLO_PROJECT_NAME, if any.
find_sigillo_project() {
  sig projects 2>/dev/null | awk -v want="$SIGILLO_PROJECT_NAME" '
    /^ *- id: "/ { id = $0; gsub(/^ *- id: "|".*$/, "", id) }
    /^ *name: "/ { name = $0; gsub(/^ *name: "|".*$/, "", name); if (name == want) print id }' | head -n1
}

# copy_secret NAME LOMBARDI_ENV SITE_ENV pipes NAME from Lombardi's Sigillo
# into the site's, never printing it; falls back to a hidden paste.
copy_secret() {
  local name="$1" from="$2" to="$3" value=""
  if has_secret "$to" "$name"; then
    say "$name is already in the site's $to environment; keeping it."
    return
  fi
  value=$(sig secrets get "$name" -p "$LOMBARDI_SIGILLO_PROJECT" --env "$from" --raw --force 2>/dev/null) || value=""
  if [[ -z "$value" ]]; then
    warn "Couldn't read $name from Lombardi's Sigillo ($from)."
    ask_secret value "Paste $name instead:"
  fi
  [[ -n "$value" ]] || { warn "No value for $name; stopping."; exit 1; }
  printf '%s' "$value" | site pnpm --silent exec gq sigillo secrets "$to" set "$name" >/dev/null
  value=""
  printf '  %s✓ stored%s %s in Sigillo (%s)\n' "$GREEN" "$RESET" "$name" "$to"
}

# registry_accepts ENVIRONMENT: the proxy answers 200 to the Composer login in
# the site's Sigillo ENVIRONMENT (local or staging). Prints nothing secret.
registry_accepts() {
  # shellcheck disable=SC2016 # JavaScript, not shell
  site pnpm --silent exec gq sigillo run "$1" -- node -e '
    const login = JSON.parse(process.env.COMPOSER_AUTH ?? "{}")["http-basic"]?.["proxy.composer.getquick.io"];
    if (!login) process.exit(1);
    const authorization = "Basic " + Buffer.from(`${login.username}:${login.password}`).toString("base64");
    fetch("https://proxy.composer.getquick.io/packages.json", { headers: { authorization } })
      .then((response) => process.exit(response.status === 200 ? 0 : 1), () => process.exit(1));
  ' >/dev/null 2>&1
}

# wait_for_registry ENVIRONMENT: the proxy picks up a new login only once its
# redeploy has propagated, so a Composer install straight after `client add`
# gets HTTP 401. Waits up to two minutes, then offers to keep waiting.
wait_for_registry() {
  local tries=0
  until registry_accepts "$1"; do
    tries=$((tries + 1))
    if (( tries % 24 == 0 )); then
      warn "The registry proxy still rejects the $1 login."
      confirm "Keep waiting?" || exit 1
    fi
    sleep 5
  done
  printf '  %s✓%s the registry proxy accepts the %s login\n' "$GREEN" "$RESET" "$1"
}

# wait_for_release TAG: watches the CI Workflow until the human says the
# tag's run finished, then checks Ploi deployed exactly the tagged commit.
wait_for_release() {
  local tag="$1" sha
  sha=$(site git rev-parse "$tag^{commit}")
  say "The push started CI for $tag ($sha). A tag run checks, then deploys the CMS and the Frontend."
  note "It takes several minutes. Each refresh lists the CI Workflow runs."
  run pnpm --silent ci:runs
  until confirm "Has the newest run finished (complete or errored)?"; do run pnpm --silent ci:runs; done
  if site pnpm --silent ploi:log 2>/dev/null | grep -q "GQ_SMOKE_DEPLOY_STATUS=success SHA=$sha"; then
    printf '  %s✓%s Ploi deployed %s (%s)\n' "$GREEN" "$RESET" "$tag" "$sha"
  else
    warn "Ploi's recent deploy logs don't show GQ_SMOKE_DEPLOY_STATUS=success SHA=$sha."
    note "Read them with: (cd $SITE_DIR && pnpm ploi:log). The CI run's logs are in the dashboard:"
    open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/workers/services/view/$PROJECT-ci/production"
    confirm "Continue anyway?" || exit 1
  fi
}

banner "gq-smoke: generate, verify, provision and release (phase 2 gate)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this run needs."
missing=()
for tool in git gh node pnpm npx php composer curl; do
  command -v "$tool" >/dev/null 2>&1 || missing+=("$tool")
done
if (( ${#missing[@]} )); then
  warn "Missing: ${missing[*]}. Install them and re-run."
  exit 1
fi
gh auth status >/dev/null 2>&1 || { warn "gh isn't logged in: run gh auth login, then re-run."; exit 1; }
GQ_VERSION=$(node -p "require('$REPO_ROOT/package.json').version")
if ! npm view "@getquick/site@$GQ_VERSION" version >/dev/null 2>&1; then
  warn "@getquick/site $GQ_VERSION (this checkout) isn't on npm yet."
  say "The gate proves the published package: release it first (README → Releasing), then re-run."
  exit 1
fi
printf '  %s✓%s tools present; @getquick/site %s is published\n' "$GREEN" "$RESET" "$GQ_VERSION"
ask SITE_DIR "Where should the site live? (default $(dirname "$REPO_ROOT")/$PROJECT)"
SITE_DIR="${SITE_DIR:-$(dirname "$REPO_ROOT")/$PROJECT}"
write_env SITE_DIR "$SITE_DIR"
ask REGISTRY_DIR "Your getquick-registry checkout? (default $(dirname "$REPO_ROOT")/getquick-registry)"
REGISTRY_DIR="${REGISTRY_DIR:-$(dirname "$REPO_ROOT")/getquick-registry}"
[[ -f "$REGISTRY_DIR/package.json" ]] || { warn "No checkout at $REGISTRY_DIR; clone Quick-Release/getquick-registry and re-run."; exit 1; }
write_env REGISTRY_DIR "$REGISTRY_DIR"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GitHub repository"
if gh repo view "$REPOSITORY" >/dev/null 2>&1; then
  say "$REPOSITORY already exists (kept from an earlier run); reusing it."
else
  say "Creates the private repository $REPOSITORY. It is kept after teardown, for repeat runs."
  confirm "Create $REPOSITORY now?" || { warn "The run needs it; stopping."; exit 1; }
  gh repo create "$REPOSITORY" --private --description "Throwaway GETQUICK content site for blueprint smoke runs (gq new)"
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Generate the site"
if [[ -f "$SITE_DIR/gq.ops.json" ]]; then
  say "$SITE_DIR already has a gq.ops.json; reusing it instead of generating again."
  note "To generate afresh, delete that directory and re-run."
else
  say "Generating $PROJECT with the published @getquick/site $GQ_VERSION, then installing it."
  mkdir -p "$(dirname "$SITE_DIR")"
  (cd "$(dirname "$SITE_DIR")" && npx --yes "@getquick/site@$GQ_VERSION" new "$(basename "$SITE_DIR")" --project "$PROJECT" --variant content)
fi
run pnpm install
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Sigillo project"
say "$PROJECT gets its own Sigillo project with the environments dev, ops and staging."
if ! sig me >/dev/null 2>&1; then
  say "Log in to Sigillo for this checkout (device flow, opens the browser)."
  sig login --scope .
fi
SIGILLO_PROJECT_ID=$(find_sigillo_project || true)
if [[ -z "$SIGILLO_PROJECT_ID" ]]; then
  confirm "Create the Sigillo project \"$SIGILLO_PROJECT_NAME\" in the GETQUICK org?" || exit 1
  sig projects create --org "$SIGILLO_ORG" --name "$SIGILLO_PROJECT_NAME"
  SIGILLO_PROJECT_ID=$(find_sigillo_project || true)
fi
if [[ -z "$SIGILLO_PROJECT_ID" ]]; then
  warn "Couldn't find the new project's ID in the listing above."
  ask SIGILLO_PROJECT_ID "Paste the project ID of \"$SIGILLO_PROJECT_NAME\":"
fi
write_env SIGILLO_PROJECT_ID "$SIGILLO_PROJECT_ID"
environments=$(sig environments -p "$SIGILLO_PROJECT_ID")
for pair in dev:Dev ops:Ops staging:Staging; do
  slug=${pair%%:*}
  if grep -q "slug: \"$slug\"" <<<"$environments"; then
    printf '  %s✓%s environment %s exists\n' "$GREEN" "$RESET" "$slug"
  else
    sig environments create -p "$SIGILLO_PROJECT_ID" --name "${pair#*:}" --slug "$slug"
  fi
done
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Fill in gq.ops.json"
say "Writes the site's public values: the Sigillo project, the $CF_ZONE_NAME hosts, Lombardi's"
say "Ploi server and Cloudflare account, and the $PROJECT buckets, Worker and repository."
say "Then gq sync renders the deploy wiring from them. No secrets are written."
# shellcheck disable=SC2016 # JavaScript, not shell
SIGILLO_PROJECT_ID="$SIGILLO_PROJECT_ID" node --input-type=module -e '
  import { readFileSync, writeFileSync } from "node:fs";
  const path = process.argv[1];
  const [project, admin, frontend, media, server, account, zone, zoneName, repository] = process.argv.slice(2);
  const ops = JSON.parse(readFileSync(path, "utf8"));
  const name = project.replace(/-/g, "_");
  Object.assign(ops, {
    sigillo: {
      apiUrl: "https://secrets.getquick.io",
      projectId: process.env.SIGILLO_PROJECT_ID,
      environments: { local: "dev", operations: "ops", staging: "staging" },
    },
    domains: { admin, frontend },
    ploi: {
      serverId: server,
      ...(ops.ploi?.siteId ? { siteId: ops.ploi.siteId } : {}),
      systemUser: project.replace(/-/g, ""),
      projectRoot: "/",
      webDirectory: "/apps/cms/web",
      database: `${name}_staging`,
      envTemplate: "apps/cms/.env.production.example",
      deployScript: "deploy/ploi/admin.sh",
    },
    releases: { bucket: `${project}-releases`, prefix: "admin/" },
    media: { bucket: `${project}-media`, domain: media },
    backups: { bucket: `${project}-releases`, prefix: "db/" },
    local: { adminEmail: "dev@tipme.to" },
    artifacts: { namespace: project, repo: project },
    ci: { worker: `${project}-ci`, backupBucket: `${project}-ci-backups` },
    cloudflare: { accountId: account, zoneId: zone, zoneName },
    github: { repository },
  });
  writeFileSync(path, `${JSON.stringify(ops, null, 2)}\n`);
' "$SITE_DIR/gq.ops.json" "$PROJECT" "$ADMIN_HOST" "$FRONTEND_HOST" "$MEDIA_HOST" \
  "$PLOI_SERVER_ID" "$CF_ACCOUNT_ID" "$CF_ZONE_ID" "$CF_ZONE_NAME" "$REPOSITORY"
printf '  %s✓ wrote%s %s/gq.ops.json\n' "$GREEN" "$RESET" "$SITE_DIR"
run pnpm exec gq sync
run pnpm install
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Shared secrets"
say "Two account-level secrets come from Lombardi's Sigillo, piped straight into"
say "$PROJECT's (never printed): the Cloudflare token-manager token and the Ploi API token."
copy_secret CLOUDFLARE_TOKEN_MANAGER_API_TOKEN ops operations
copy_secret PLOI_API_TOKEN staging staging
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Composer registry logins"
say "$PROJECT gets its own logins to the GETQUICK Composer registry: client $PROJECT"
say "(staging: CI and Ploi) and $PROJECT-dev (dev: local installs). The registry CLI"
say "stores each as COMPOSER_AUTH in $PROJECT's Sigillo and redeploys the proxy."
note "Needs \`pnpm registry login\` done once in $REGISTRY_DIR."
for pair in staging:staging:$PROJECT dev:local:$PROJECT-dev; do
  IFS=: read -r slug alias client <<<"$pair"
  if has_secret "$alias" COMPOSER_AUTH; then
    say "COMPOSER_AUTH is already in $slug; keeping it."
    continue
  fi
  printf '  %s$ pnpm registry client add %s --project %s --env %s%s\n' "$DIM" "$client" "$SIGILLO_PROJECT_ID" "$slug" "$RESET"
  until (cd "$REGISTRY_DIR" && pnpm registry client add "$client" --project "$SIGILLO_PROJECT_ID" --env "$slug"); do
    warn "That failed (not logged in? run pnpm registry login in $REGISTRY_DIR)."
    confirm "Retry?" || exit 1
  done
done
say "Waiting for the registry proxy to accept both logins (its redeploy takes a moment)."
wait_for_registry staging
wait_for_registry local
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Verify locally (acceptance: pnpm verify passes)"
say "Installs the CMS's Composer dependencies from the registry (writing composer.lock),"
say "then runs every check the pre-push hook and CI run."
run pnpm cms:composer
run pnpm verify
printf '  %s✓%s pnpm verify passed\n' "$GREEN" "$RESET"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Push to GitHub"
if [[ -n "$(site git status --porcelain)" ]]; then
  run git add -A
  run git commit -m "feat: generate $PROJECT with gq new ($GQ_VERSION)"
fi
run git branch -M main
site git remote get-url origin >/dev/null 2>&1 || run git remote add origin "https://github.com/$REPOSITORY.git"
if [[ -n "$(site git ls-remote --heads origin main)" ]] && ! site git merge-base --is-ancestor "$(site git ls-remote --heads origin main | cut -f1)" HEAD 2>/dev/null; then
  warn "$REPOSITORY already has a main this checkout doesn't contain (an earlier run's)."
  confirm "Force-push this site over it?" || exit 1
  tags=$(site git ls-remote --tags --refs origin 'v*' | sed 's|.*refs/tags/||')
  if [[ -n "$tags" ]] && confirm "Also delete the earlier run's tags ($(tr '\n' ' ' <<<"$tags"))?"; then
    # shellcheck disable=SC2086
    run git push origin --delete $tags
  fi
  run git push --force -u origin main
else
  run git push -u origin main
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "DNS for the CMS host"
say "Ploi's Let's Encrypt certificate needs $ADMIN_HOST to resolve to the Ploi server."
server_json=$(site pnpm --silent ops ploi server show --json 2>/dev/null || true)
SERVER_IP=$(grep -oE '"ip": *"[0-9.]+"' <<<"$server_json" | grep -oE '[0-9.]{7,}' | head -n1 || true)
[[ -n "$SERVER_IP" ]] || ask SERVER_IP "Couldn't read the server's IP; paste Ploi server $PLOI_SERVER_ID's IPv4:"
open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/$CF_ZONE_NAME/dns/records"
step "Add record → Type A → Name: $PROJECT-cms → IPv4 address: $SERVER_IP"
step "Proxy status: off (grey cloud, DNS only), so Let's Encrypt reaches the server → Save."
until [[ "$(node -e "require('dns').promises.resolve4('$ADMIN_HOST').then(a => console.log(a.join(' ')), () => {})")" == *"$SERVER_IP"* ]]; do
  warn "$ADMIN_HOST doesn't resolve to $SERVER_IP yet."
  confirm "Check again?" || { warn "Continuing: ploi provision will skip the certificate until it does."; break; }
done
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Ploi site"
say "Creates the system user, the site $ADMIN_HOST, the database, its .env, the deploy"
say "script and the certificate on Lombardi's server. It shows the plan and asks first."
run pnpm ploi:provision
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Cloudflare resources"
say "Each command mints its scoped GETQUICK GQ-SMOKE token into Sigillo staging:"
step "deploy-token: the Frontend's Alchemy deploy token"
step "releases: the $PROJECT-releases bucket and its key"
step "media: the $PROJECT-media bucket on https://$MEDIA_HOST, and its key"
step "ploi:media: writes the media key into the Ploi site's .env (S3_UPLOADS_*)"
step "ci: the Artifacts repo, the $PROJECT-ci-backups bucket and the CI deploy token"
run pnpm cf:deploy-token
run pnpm cf:releases
run pnpm cf:media
run pnpm ploi:media
run pnpm cf:ci
pause

# ── 13 ────────────────────────────────────────────────────────────────────
stage "GitHub → CI Worker"
say "github:setup stores a webhook secret and asks for a fine-grained GitHub token."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: $PROJECT CI · Resource owner: Quick-Release · Only select repositories: $PROJECT"
step "Permissions: Contents → Read-only, Commit statuses → Read and write → Generate, copy it."
say "Paste it when github:setup asks (hidden). Then ci:deploy deploys $PROJECT-ci with its secrets."
run pnpm github:setup
run pnpm ci:deploy
if [[ -n "$(site git status --porcelain)" ]]; then
  say "Provisioning recorded values in gq.ops.json (the Ploi site ID); committing them."
  run git add -A
  run git commit -m "chore: record $PROJECT's provisioned IDs"
  run git push
fi
pause

# ── 14 ────────────────────────────────────────────────────────────────────
stage "First release"
say "pnpm push minor bumps the version, runs the checks, commits, tags and pushes."
note "The first CMS deploy installs Bedrock only; WordPress is installed in the next stage."
run pnpm push minor
FIRST_TAG=$(site git describe --tags --abbrev=0)
wait_for_release "$FIRST_TAG"
pause

# ── 15 ────────────────────────────────────────────────────────────────────
stage "Install WordPress and a front page"
open_url "https://$ADMIN_HOST/wp/wp-admin/install.php"
step "Site title: GQ Smoke · pick an admin user and a strong password (keep them in your password manager)."
step "Log in, then Pages → Add New: give it a unique title, e.g. Smoke $(date +%Y-%m-%d), and Publish."
step "Settings → Reading → Your homepage displays: A static page → Homepage: that page → Save."
ask SMOKE_MARKER "The front page's exact title:"
write_env SMOKE_MARKER "$SMOKE_MARKER"
pause

# ── 16 ────────────────────────────────────────────────────────────────────
stage "Second release and confirm on the hosts"
say "Now WordPress is installed, this release's deploy activates the theme and plugins (WPGraphQL among them)."
run pnpm push fix
SECOND_TAG=$(site git describe --tags --abbrev=0)
wait_for_release "$SECOND_TAG"
graphql=$(curl -sS -X POST "https://$ADMIN_HOST/wp/graphql" -H 'Content-Type: application/json' \
  -d '{"query":"{ generalSettings { title } nodeByUri(uri: \"/\") { ... on Page { title } } }"}' || true)
frontend=$(curl -sS "https://$FRONTEND_HOST/" || true)
passed=1
if grep -qF "$SMOKE_MARKER" <<<"$graphql"; then
  printf '  %s✓%s CMS: https://%s/wp/graphql answers with the front page "%s"\n' "$GREEN" "$RESET" "$ADMIN_HOST" "$SMOKE_MARKER"
else
  passed=0; warn "CMS: /wp/graphql didn't return \"$SMOKE_MARKER\": ${graphql:0:300}"
fi
if grep -qF "$SMOKE_MARKER" <<<"$frontend"; then
  printf '  %s✓%s Frontend: https://%s renders "%s" from the CMS\n' "$GREEN" "$RESET" "$FRONTEND_HOST" "$SMOKE_MARKER"
else
  passed=0; warn "Frontend: https://$FRONTEND_HOST doesn't show \"$SMOKE_MARKER\"."
fi
open_url "https://$FRONTEND_HOST/"
if (( passed )); then
  say "Phase 2 gate passed: $SECOND_TAG deployed the CMS and the Frontend through Cloudflare CI."
  note "Record it in docs/plans/getquick-blueprint-rollout.md, then tear down: scripts/smoke/gq-smoke-down.sh"
else
  SKIPPED+=("the host checks for $SECOND_TAG failed; the gate hasn't passed")
fi
pause

finish
