#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
# Any key continues; the rest of a multi-byte key (an arrow) is discarded.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press any key to continue}" "$RESET"
  read -rsn1 _ || true
  read -rsn100 -t 0.05 _ || true
  printf '\n'
}

# confirm "question" is a Y/n gate; Enter (or anything but n) means yes.
confirm() {
  local reply=""
  printf '  %s? %s [Y/n]%s ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
  [[ ! "$reply" =~ ^[Nn] ]]
}

# confirm_default_no "question" is a y/N gate for irreversible actions and for
# going on past a failed check: Enter means no.
confirm_default_no() {
  local reply=""
  printf '  %s? %s [y/N]%s ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# gq-smoke, down: tears down the infrastructure scripts/smoke/gq-smoke-up.sh
# provisioned (#7): the Frontend and CI Workers, the GitHub webhook, the R2
# buckets, the Frontend's D1 publication store and the Artifacts repo, the Ploi site, database and system user, the
# CMS DNS record, and the GETQUICK GQ-SMOKE tokens. Keeps the GitHub
# repository, the Sigillo project and the registry logins for repeat runs.
#
# Run from anywhere: scripts/smoke/gq-smoke-down.sh. Re-running is safe:
# anything already gone is reported and skipped.

TOTAL_STAGES=10

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/gq-smoke"
mkdir -p "$STATE_DIR"
ENV_FILE="$STATE_DIR/wizard.env"
CLEANUP="$REPO_ROOT/scripts/smoke/cloudflare-cleanup.mjs"

PROJECT=gq-smoke
REPOSITORY=Quick-Release/gq-smoke
CF_ACCOUNT_ID=8f38791a8c37b182239af2a385ab3c31
CF_ZONE_NAME=bnq.pt
ADMIN_HOST=$PROJECT-cms.$CF_ZONE_NAME
FRONTEND_HOST=$PROJECT-fe.$CF_ZONE_NAME
MEDIA_HOST=$PROJECT-media.$CF_ZONE_NAME
BUCKETS=("$PROJECT-releases" "$PROJECT-media" "$PROJECT-ci-backups")

site() { (cd "$SITE_DIR" && "$@"); }

run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  until site "$@"; do
    warn "That failed."
    confirm "Retry?" || { warn "Stopped. Fix it and re-run the wizard: finished stages are skipped."; exit 1; }
  done
}

# try CMD...: like run, but a failure (usually "already gone") is reported and skipped.
try() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  site "$@" || note "(failed or already gone; continuing)"
}

# wrangler ARGS...: the site's Wrangler on your own OAuth login, never a
# CLOUDFLARE_API_TOKEN from the shell.
wrangler() {
  site env -u CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID" \
    ./infra/ci/node_modules/.bin/wrangler "$@"
}

# ploi_id OPERATION NAME: the ID of the Ploi resource named NAME in a list operation's JSON.
ploi_id() {
  site pnpm --silent ops ploi api "$1" --all 2>/dev/null | node -e '
    let text = ""; process.stdin.on("data", (chunk) => (text += chunk)).on("end", () => {
      const start = text.search(/^[\[{]/m);
      if (start < 0) return;
      const data = JSON.parse(text.slice(start));
      const list = Array.isArray(data) ? data : (data.data ?? []);
      const found = list.find((entry) => entry.name === process.argv[1] || entry.domain === process.argv[1]);
      if (found) console.log(found.id);
    });' "$2"
}

banner "gq-smoke: tear down the throwaway infrastructure"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
ask SITE_DIR "The gq-smoke site checkout? (default $(dirname "$REPO_ROOT")/$PROJECT)"
SITE_DIR="${SITE_DIR:-$(dirname "$REPO_ROOT")/$PROJECT}"
[[ -f "$SITE_DIR/gq.ops.json" ]] || { warn "No gq.ops.json in $SITE_DIR."; exit 1; }
write_env SITE_DIR "$SITE_DIR"
[[ "$(node -p "require('$SITE_DIR/gq.ops.json').project")" == "$PROJECT" ]] || { warn "$SITE_DIR isn't the $PROJECT site."; exit 1; }
for tool in gh node pnpm; do command -v "$tool" >/dev/null 2>&1 || { warn "Missing: $tool"; exit 1; }; done
[[ -x "$SITE_DIR/infra/ci/node_modules/.bin/wrangler" ]] || run pnpm install
warn "This permanently deletes $PROJECT's Workers, buckets (and their objects), D1 store, Ploi site and"
warn "database, DNS record and tokens. The repository and Sigillo project are kept."
confirm_default_no "Tear down $PROJECT?" || exit 1

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Frontend Worker"
say "alchemy destroy removes the $PROJECT-fe Worker and its $FRONTEND_HOST domain,"
say "with the Staging Alchemy token from Sigillo. Alchemy's shared state store is kept."
note "Its D1 publication store is retained (a prod-stage store always is); stage 6 deletes it."
run pnpm exec gq sigillo run staging -- env CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID" \
  pnpm --dir infra exec alchemy destroy --stage prod --config frontend.run.ts --yes
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "CI Worker"
say "The CI Worker, its Workflows and its sandbox containers go with your own Wrangler"
say "login (OAuth in the browser), which also deletes the buckets later."
whoami=$(wrangler whoami 2>&1 || true)
if grep -qi "not authenticated" <<<"$whoami"; then wrangler login; fi
try wrangler delete "$PROJECT-ci"
for workflow in "$PROJECT-ci" "$PROJECT-mirror"; do
  try wrangler workflows delete "$workflow"
done
say "Container applications left behind (should be none named $PROJECT):"
containers=$(wrangler containers list 2>/dev/null || true)
grep -i "$PROJECT" <<<"$containers" || note "(none)"
# shellcheck disable=SC2013 # IDs, one word each
for id in $(grep -i "$PROJECT" <<<"$containers" | grep -oE '[0-9a-f]{8}-[0-9a-f-]{27}' | sort -u); do
  confirm_default_no "Delete container application $id?" && try wrangler containers delete "$id"
done
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "GitHub webhook"
say "Removes $REPOSITORY's push webhook to the deleted CI Worker (the repository stays)."
for hook in $(gh api "repos/$REPOSITORY/hooks" --jq ".[] | select(.config.url | contains(\"$PROJECT-ci\")) | .id"); do
  gh api -X DELETE "repos/$REPOSITORY/hooks/$hook" && printf '  %s✓ deleted%s webhook %s\n' "$GREEN" "$RESET" "$hook"
done
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Empty the R2 buckets"
say "Deletes every object with each bucket's own scoped key from Sigillo staging,"
say "which can't touch any other bucket."
run pnpm exec gq sigillo run staging -- node "$CLEANUP" empty-bucket "$PROJECT-releases" R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY
run pnpm exec gq sigillo run staging -- node "$CLEANUP" empty-bucket "$PROJECT-media" S3_UPLOADS_KEY S3_UPLOADS_SECRET
run pnpm exec gq sigillo run staging -- node "$CLEANUP" empty-bucket "$PROJECT-ci-backups" CI_BACKUP_R2_ACCESS_KEY_ID CI_BACKUP_R2_SECRET_ACCESS_KEY
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Delete the buckets, the publication store and the Artifacts repo"
try wrangler r2 bucket domain remove "$PROJECT-media" --domain "$MEDIA_HOST" --force
for bucket in "${BUCKETS[@]}"; do
  try wrangler r2 bucket delete "$bucket"
done
try wrangler d1 delete "$PROJECT-fe-publications" --skip-confirmation
try wrangler artifacts repos delete "$PROJECT" --namespace "$PROJECT" --force
note "The empty Artifacts namespace $PROJECT stays: Wrangler has no command to delete one."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Ploi site, database and system user"
SITE_ID=$(node -p "require('$SITE_DIR/gq.ops.json').ploi?.siteId ?? ''")
if [[ -n "$SITE_ID" ]]; then
  say "Deleting the Ploi site $ADMIN_HOST ($SITE_ID); Ploi asks you to confirm."
  run pnpm --silent ops ploi api sites.delete-site
else
  say "gq.ops.json records no Ploi site; skipping it."
fi
DATABASE_ID=$(ploi_id databases.list-databases "$(node -p "require('$SITE_DIR/gq.ops.json').ploi.database")" || true)
[[ -n "$DATABASE_ID" ]] && run pnpm --silent ops ploi api databases.delete-database --path "id=$DATABASE_ID"
USER_ID=$(ploi_id system-users.list-system-users "$(node -p "require('$SITE_DIR/gq.ops.json').ploi.systemUser")" || true)
[[ -n "$USER_ID" ]] && run pnpm --silent ops ploi api system-users.delete-system-user --path "systemUser=$USER_ID"
if [[ -n "$SITE_ID" ]]; then
  say "Forgetting the deleted site ID in gq.ops.json, so the next run's ploi:provision creates a new one."
  node -e '
    const fs = require("fs"); const path = process.argv[1];
    const ops = JSON.parse(fs.readFileSync(path, "utf8")); delete ops.ploi.siteId;
    fs.writeFileSync(path, JSON.stringify(ops, null, 2) + "\n");' "$SITE_DIR/gq.ops.json"
  run git commit -m "chore: forget the torn-down Ploi site" -- gq.ops.json
  run git push
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "CMS DNS record"
open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/$CF_ZONE_NAME/dns/records"
step "Search $PROJECT → delete the A record $PROJECT-cms (and any other $PROJECT record left)."
pause "Press any key once it's deleted"
say "Records left in $CF_ZONE_NAME for $PROJECT's hosts (should be none):"
for host in "$ADMIN_HOST" "$FRONTEND_HOST" "$MEDIA_HOST"; do
  try pnpm --silent ops cloudflare dns list --name "$host"
done
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare tokens"
say "The GETQUICK GQ-SMOKE tokens, deleted last since the stages above used them:"
run pnpm exec gq sigillo run operations -- node "$CLEANUP" tokens
if confirm_default_no "Delete these tokens?"; then
  run pnpm exec gq sigillo run operations -- node "$CLEANUP" tokens --delete
fi
note "Their values stay in Sigillo staging; the next run's cf:* commands create new tokens over them."
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Check nothing is left (acceptance)"
# leftover KIND COUNT: reports how many KIND named $PROJECT are left, and
# carries any into the closing summary.
leftover() {
  if [[ "$2" == 0 ]]; then
    printf '  %s✓%s %s named %s: exactly 0\n' "$GREEN" "$RESET" "$1" "$PROJECT"
  else
    warn "$1 named $PROJECT: $2"
    SKIPPED+=("delete the $2 remaining $PROJECT $1")
  fi
}
if buckets=$(wrangler r2 bucket list 2>/dev/null); then
  leftover "R2 buckets" "$(grep -ci "$PROJECT" <<<"$buckets" || true)"
else
  warn "Couldn't list the R2 buckets."; SKIPPED+=("check the R2 buckets by hand (listing failed)")
fi
if databases=$(wrangler d1 list 2>/dev/null); then
  leftover "D1 databases" "$(grep -ci "$PROJECT" <<<"$databases" || true)"
else
  warn "Couldn't list the D1 databases."; SKIPPED+=("check the $PROJECT-fe-publications D1 database by hand (listing failed)")
fi
if tokens=$(site pnpm --silent exec gq sigillo run operations -- node "$CLEANUP" tokens 2>/dev/null); then
  leftover "Cloudflare tokens" "$(grep -c '^found' <<<"$tokens" || true)"
else
  warn "Couldn't list the Cloudflare tokens."; SKIPPED+=("check the GETQUICK GQ-SMOKE tokens by hand (listing failed)")
fi
if sites=$(site pnpm --silent ops ploi sites list 2>/dev/null); then
  leftover "Ploi sites" "$(grep -ci "$PROJECT" <<<"$sites" || true)"
else
  warn "Couldn't list the Ploi sites."; SKIPPED+=("check the Ploi sites by hand (listing failed)")
fi
records=0
for host in "$ADMIN_HOST" "$FRONTEND_HOST" "$MEDIA_HOST"; do
  [[ -n "$(node -e "require('dns').promises.resolve4('$host').then(a => console.log(a[0]), () => {})")" ]] && records=$((records + 1))
done
leftover "DNS hosts" "$records"
open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/workers-and-pages"
step "Workers & Pages: search $PROJECT and count the Workers ($PROJECT-fe, $PROJECT-ci)."
if confirm "Workers named $PROJECT in the dashboard: exactly 0?"; then
  leftover "Workers" 0
else
  warn "Workers named $PROJECT remain."; SKIPPED+=("delete the remaining $PROJECT Worker(s) in the dashboard")
fi
(( ${#SKIPPED[@]} )) || note "Teardown complete. Kept for repeat runs: $REPOSITORY, the Sigillo project, the registry logins."
if confirm "Log Wrangler out of your Cloudflare account again?"; then
  wrangler logout
fi

finish
